#!/usr/bin/env python3
"""
Generate Professional PDF Audit Reports from Website LLM Analyzer Results.

Creates branded, client-ready PDF reports with charts, tables, and analytics
from audit JSON outputs and cross-reference analysis files.

Author: Website LLM Analyzer Team
Created: 2026-02-12
Version: 1.0

Usage:
    python generate_report.py --website example.com --audit SEO_AUDIT
    python generate_report.py --website example.com --audit SEO_AUDIT --preview
    python generate_report.py --website example.com --audit SEO_AUDIT --logo logo.png --company "My Agency"
"""

import os
import re
import json
import math
import logging
import argparse
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any, Optional, Tuple
from collections import Counter, defaultdict

# ReportLab imports
from reportlab.lib.pagesizes import A4, LETTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm, cm, inch
from reportlab.lib import colors
from reportlab.lib.colors import HexColor, Color
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, Image, KeepTogether, ListFlowable, ListItem,
    Flowable, NextPageTemplate, PageTemplate, Frame
)
from reportlab.pdfgen import canvas
from reportlab.graphics.shapes import Drawing, Rect, Circle, Line, String, Wedge
from reportlab.graphics.charts.barcharts import VerticalBarChart, HorizontalBarChart
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics import renderPDF

# Import project logger if available
try:
    from core.logger import get_logger
    logger = get_logger(__name__)
except ImportError:
    import logging
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
    logger = logging.getLogger(__name__)


# ============================================================================
# CONSTANTS & CONFIGURATION
# ============================================================================

VERSION = "1.0.0"

# Default colors (can be overridden via --color-scheme)
DEFAULT_PRIMARY_COLOR = "#2563eb"  # Blue
DEFAULT_SECONDARY_COLOR = "#64748b"  # Slate gray

# Severity colors
SEVERITY_COLORS = {
    'critical': HexColor("#dc2626"),  # Red
    'major': HexColor("#f97316"),     # Orange
    'minor': HexColor("#eab308"),     # Yellow
    'opportunity': HexColor("#22c55e"),  # Green
    'info': HexColor("#3b82f6"),      # Blue
    'high': HexColor("#dc2626"),
    'medium': HexColor("#f97316"),
    'low': HexColor("#eab308"),
}

# Score bucket colors
SCORE_COLORS = {
    'excellent': HexColor("#22c55e"),   # Green (85-100)
    'good': HexColor("#84cc16"),        # Lime (70-84)
    'needs_work': HexColor("#eab308"),  # Yellow (50-69)
    'poor': HexColor("#ef4444"),        # Red (0-49)
}

# Multi-language support
TRANSLATIONS = {
    "en": {
        "executive_summary": "Executive Summary",
        "key_findings": "Key Findings",
        "score_distribution": "Score Distribution",
        "recommendations": "Recommendations",
        "methodology": "Methodology",
        "appendix": "Appendix",
        "table_of_contents": "Table of Contents",
        "page": "Page",
        "pages_analyzed": "Pages Analyzed",
        "overall_score": "Overall Score",
        "top_pages": "Top Performing Pages",
        "bottom_pages": "Pages Needing Attention",
        "issues_by_severity": "Issues by Severity",
        "issues_by_category": "Issues by Category",
        "quick_wins": "Quick Wins",
        "detailed_results": "Detailed Page Results",
        "strengths": "Strengths",
        "issues": "Issues",
        "severity": "Severity",
        "issue": "Issue",
        "recommendation": "Recommendation",
        "impact": "Impact",
        "score": "Score",
        "url": "URL",
        "confidential": "Confidential",
        "generated_by": "Generated by Website LLM Analyzer",
        "audit_type": "Audit Type",
        "date": "Date",
        "prepared_by": "Prepared by",
        "website_audit_report": "Website Audit Report",
        "full_page_list": "Full Page List",
        "content_gaps": "Content Gaps",
        "priority_actions": "Priority Actions",
        "site_wide_issues": "Site-Wide Issues",
        # GEO audit specific
        "ai_citation_likelihood": "AI Citation Likelihood",
        "quotable_excerpts": "Quotable Excerpts",
        "entities_detected": "Entities Detected",
        "optimization_opportunities": "Optimization Opportunities",
        # Greenwashing specific
        "violations": "Violations",
        "compliance_status": "Compliance Status",
        "afm_principle": "AFM Principle",
        # Spelling/Grammar
        "errors": "Errors",
        "error_type": "Error Type",
        "corrections": "Corrections",
        # Kantar
        "meaningful_score": "Meaningful Score",
        "different_score": "Different Score",
        "strategic_gaps": "Strategic Gaps",
    },
    "nl": {
        "executive_summary": "Management Samenvatting",
        "key_findings": "Belangrijkste Bevindingen",
        "score_distribution": "Score Verdeling",
        "recommendations": "Aanbevelingen",
        "methodology": "Methodologie",
        "appendix": "Bijlage",
        "table_of_contents": "Inhoudsopgave",
        "page": "Pagina",
        "pages_analyzed": "Geanalyseerde Pagina's",
        "overall_score": "Totaalscore",
        "top_pages": "Best Presterende Pagina's",
        "bottom_pages": "Pagina's die Aandacht Nodig Hebben",
        "issues_by_severity": "Problemen per Ernst",
        "issues_by_category": "Problemen per Categorie",
        "quick_wins": "Snelle Winsten",
        "detailed_results": "Gedetailleerde Pagina Resultaten",
        "strengths": "Sterke Punten",
        "issues": "Problemen",
        "severity": "Ernst",
        "issue": "Probleem",
        "recommendation": "Aanbeveling",
        "impact": "Impact",
        "score": "Score",
        "url": "URL",
        "confidential": "Vertrouwelijk",
        "generated_by": "Gegenereerd door Website LLM Analyzer",
        "audit_type": "Audit Type",
        "date": "Datum",
        "prepared_by": "Opgesteld door",
        "website_audit_report": "Website Audit Rapport",
        "full_page_list": "Volledige Paginalijst",
        "content_gaps": "Inhoudelijke Hiaten",
        "priority_actions": "Prioritaire Acties",
        "site_wide_issues": "Sitebrede Problemen",
        "ai_citation_likelihood": "AI Citatie Waarschijnlijkheid",
        "quotable_excerpts": "Citeerbare Fragmenten",
        "entities_detected": "Gedetecteerde Entiteiten",
        "optimization_opportunities": "Optimalisatie Mogelijkheden",
        "violations": "Overtredingen",
        "compliance_status": "Nalevingsstatus",
        "afm_principle": "AFM Principe",
        "errors": "Fouten",
        "error_type": "Fouttype",
        "corrections": "Correcties",
        "meaningful_score": "Betekenis Score",
        "different_score": "Onderscheidend Score",
        "strategic_gaps": "Strategische Hiaten",
    },
    "ro": {
        "executive_summary": "Rezumat Executiv",
        "key_findings": "Constatări Cheie",
        "score_distribution": "Distribuția Scorurilor",
        "recommendations": "Recomandări",
        "methodology": "Metodologie",
        "appendix": "Anexă",
        "table_of_contents": "Cuprins",
        "page": "Pagina",
        "pages_analyzed": "Pagini Analizate",
        "overall_score": "Scor General",
        "top_pages": "Pagini cu Cele Mai Bune Performanțe",
        "bottom_pages": "Pagini Care Necesită Atenție",
        "issues_by_severity": "Probleme după Severitate",
        "issues_by_category": "Probleme după Categorie",
        "quick_wins": "Câștiguri Rapide",
        "detailed_results": "Rezultate Detaliate per Pagină",
        "strengths": "Puncte Forte",
        "issues": "Probleme",
        "severity": "Severitate",
        "issue": "Problemă",
        "recommendation": "Recomandare",
        "impact": "Impact",
        "score": "Scor",
        "url": "URL",
        "confidential": "Confidențial",
        "generated_by": "Generat de Website LLM Analyzer",
        "audit_type": "Tip Audit",
        "date": "Data",
        "prepared_by": "Întocmit de",
        "website_audit_report": "Raport de Audit Website",
        "full_page_list": "Lista Completă a Paginilor",
        "content_gaps": "Lacune de Conținut",
        "priority_actions": "Acțiuni Prioritare",
        "site_wide_issues": "Probleme la Nivelul Site-ului",
        "ai_citation_likelihood": "Probabilitate de Citare AI",
        "quotable_excerpts": "Fragmente Citabile",
        "entities_detected": "Entități Detectate",
        "optimization_opportunities": "Oportunități de Optimizare",
        "violations": "Încălcări",
        "compliance_status": "Status Conformitate",
        "afm_principle": "Principiu AFM",
        "errors": "Erori",
        "error_type": "Tip Eroare",
        "corrections": "Corecturi",
        "meaningful_score": "Scor Semnificație",
        "different_score": "Scor Diferențiere",
        "strategic_gaps": "Lacune Strategice",
    }
}

# Audit type configurations
AUDIT_CONFIGS = {
    'seo_audit': {
        'name': 'SEO Audit',
        'type': 'score',
        'score_field': 'overall_score',
        'score_path': ['seo_audit', 'overall_score'],
        'issues_path': ['issues'],
        'quick_wins_path': ['quick_wins'],
        'content_gaps_path': ['content_gaps'],
        'extra_metrics': [
            ('content_depth_score', 'Content Depth'),
            ('eeat_score', 'E-E-A-T'),
            ('keyword_optimization_score', 'Keyword Optimization'),
            ('technical_onpage_score', 'Technical On-Page'),
            ('image_seo_score', 'Image SEO'),
        ],
        'extra_paths': {
            'content_depth_score': ['seo_audit', 'content_depth_score'],
            'eeat_score': ['seo_audit', 'eeat_score'],
            'keyword_optimization_score': ['seo_audit', 'keyword_optimization_score'],
            'technical_onpage_score': ['seo_audit', 'technical_onpage_score'],
            'image_seo_score': ['seo_audit', 'image_seo_score'],
            'search_intent': ['seo_audit', 'search_intent'],
            'estimated_useful_word_count': ['seo_audit', 'estimated_useful_word_count'],
            'cannibalization_risk': ['seo_audit', 'cannibalization_risk'],
        }
    },
    'geo_audit': {
        'name': 'GEO Audit',
        'type': 'score',
        'score_field': 'overall_score',
        'score_path': ['geo_audit', 'overall_score'],
        'issues_path': ['issues'],
        'quick_wins_path': ['recommendations'],
        'extra_metrics': [
            ('citation_probability', 'Citation Probability'),
            ('authority_score', 'Authority Score'),
            ('structure_score', 'Structure Score'),
        ],
        'extra_paths': {
            'citation_probability': ['geo_audit', 'citation_probability'],
            'authority_score': ['geo_audit', 'authority_score'],
            'structure_score': ['geo_audit', 'structure_score'],
            'factual_density_score': ['geo_audit', 'factual_density_score'],
        },
    },
    'greenwashing': {
        'name': 'Greenwashing Audit',
        'type': 'violation',
        'violations_path': ['violations'],
        'severity_field': 'afm_principle_ref',
    },
    'advertisment': {
        'name': 'Advertisement Compliance',
        'type': 'violation',
        'violations_path': ['violations'],
        'severity_field': 'severity',
    },
    'spelling_grammar': {
        'name': 'Spelling & Grammar',
        'type': 'error_count',
        'errors_path': ['spelling_grammar_audit', 'errors'],
        'category_field': 'category',
    },
    'kantar': {
        'name': 'Kantar MDS Analysis',
        'type': 'kantar',
        'meaningful_path': ['analysis', 'meaningful'],
        'different_path': ['analysis', 'different'],
    },
    'accessibility_audit': {
        'name': 'Accessibility Audit',
        'type': 'score',
        'score_field': 'overall_score',
        'score_path': ['accessibility_audit', 'overall_score'],
        'issues_path': ['issues'],
        'quick_wins_path': ['quick_wins'],
    },
    'content_quality': {
        'name': 'Content Quality',
        'type': 'score',
        'score_field': 'overall_score',
        'score_path': ['content_quality', 'overall_score'],
        'issues_path': ['issues'],
        'quick_wins_path': ['quick_wins'],
    },
    'brand_voice': {
        'name': 'Brand Voice',
        'type': 'score',
        'score_field': 'overall_score',
        'score_path': ['brand_voice_audit', 'overall_score'],
        'issues_path': ['issues'],
        'quick_wins_path': ['recommendations'],
        'extra_metrics': [
            ('consistency_score', 'Consistency Score'),
            ('distinctiveness_score', 'Distinctiveness'),
        ],
        'extra_paths': {
            'consistency_score': ['brand_voice_audit', 'consistency_score'],
            'distinctiveness_score': ['brand_voice_audit', 'distinctiveness_score'],
        },
    },
    'readability_audit': {
        'name': 'Readability Audit',
        'type': 'score',
        'score_field': 'overall_score',
        'score_path': ['readability_audit', 'overall_score'],
        'issues_path': ['issues'],
        'quick_wins_path': ['recommendations'],
    },
    'legal_gdpr': {
        'name': 'Legal GDPR',
        'type': 'score',
        'score_field': 'overall_score',
        'score_path': ['gdpr_audit', 'overall_score'],
        'issues_path': ['violations'],
        'quick_wins_path': ['recommendations'],
        'extra_metrics': [
            ('transparency_score', 'Transparency'),
            ('consent_quality_score', 'Consent Quality'),
        ],
        'extra_paths': {
            'transparency_score': ['gdpr_audit', 'transparency_score'],
            'consent_quality_score': ['gdpr_audit', 'consent_quality_score'],
        },
    },
    'ux_content': {
        'name': 'UX Content Audit',
        'type': 'score',
        'score_field': 'overall_score',
        'score_path': ['ux_content_audit', 'overall_score'],
        'issues_path': ['issues'],
        'quick_wins_path': ['recommendations'],
        'extra_metrics': [
            ('message_clarity_score', 'Message Clarity'),
            ('cta_effectiveness_score', 'CTA Effectiveness'),
        ],
        'extra_paths': {
            'message_clarity_score': ['ux_content_audit', 'message_clarity_score'],
            'cta_effectiveness_score': ['ux_content_audit', 'cta_effectiveness_score'],
            'journey_alignment_score': ['ux_content_audit', 'journey_alignment_score'],
        },
    },
    'e_commerce': {
        'name': 'E-Commerce Audit',
        'type': 'score',
        'score_field': 'overall_score',
        'score_path': ['ecommerce_audit', 'overall_score'],
        'issues_path': ['issues'],
        'quick_wins_path': ['recommendations'],
        'extra_metrics': [
            ('product_info_score', 'Product Info'),
            ('trust_signals_score', 'Trust Signals'),
        ],
        'extra_paths': {
            'product_info_score': ['ecommerce_audit', 'product_info_score'],
            'trust_signals_score': ['ecommerce_audit', 'trust_signals_score'],
            'conversion_clarity_score': ['ecommerce_audit', 'conversion_clarity_score'],
        },
    },
    'translation_quality': {
        'name': 'Translation Quality',
        'type': 'score',
        'score_field': 'overall_score',
        'score_path': ['translation_audit', 'overall_score'],
        'issues_path': ['errors'],
        'quick_wins_path': ['recommendations'],
        'extra_metrics': [
            ('accuracy_score', 'Accuracy'),
            ('fluency_score', 'Fluency'),
        ],
        'extra_paths': {
            'accuracy_score': ['translation_audit', 'accuracy_score'],
            'fluency_score': ['translation_audit', 'fluency_score'],
            'localization_score': ['translation_audit', 'localization_score'],
        },
    },
    'competitor_analysis': {
        'name': 'Competitor Analysis',
        'type': 'score',
        'score_field': 'overall_score',
        'score_path': ['competitive_positioning_audit', 'overall_score'],
        'issues_path': ['issues'],
        'quick_wins_path': ['recommendations'],
        'extra_metrics': [
            ('value_proposition_score', 'Value Proposition'),
            ('differentiation_score', 'Differentiation'),
            ('messaging_score', 'Messaging'),
            ('topical_gap_score', 'Topical Coverage'),
        ],
        'extra_paths': {
            'value_proposition_score': ['competitive_positioning_audit', 'value_proposition_score'],
            'differentiation_score': ['competitive_positioning_audit', 'differentiation_score'],
            'messaging_score': ['competitive_positioning_audit', 'messaging_score'],
            'topical_gap_score': ['competitive_positioning_audit', 'topical_gap_score'],
        },
    },
    'internal_linking': {
        'name': 'Internal Linking',
        'type': 'score',
        'score_field': 'overall_score',
        'score_path': ['internal_linking', 'overall_score'],
        'issues_path': ['issues'],
        'quick_wins_path': ['recommendations'],
        'extra_metrics': [
            ('anchor_quality_score', 'Anchor Quality'),
            ('cluster_coverage_score', 'Cluster Coverage'),
            ('link_density_score', 'Link Density'),
            ('outbound_link_score', 'Outbound Links'),
        ],
        'extra_paths': {
            'anchor_quality_score': ['internal_linking', 'anchor_quality_score'],
            'cluster_coverage_score': ['internal_linking', 'cluster_coverage_score'],
            'link_density_score': ['internal_linking', 'link_density_score'],
            'outbound_link_score': ['internal_linking', 'outbound_link_score'],
        },
    },
    'technical_seo': {
        'name': 'Technical SEO',
        'type': 'score',
        'score_field': 'overall_score',
        'score_path': ['technical_seo_audit', 'overall_score'],
        'issues_path': ['issues'],
        'quick_wins_path': ['recommendations'],
        'extra_metrics': [
            ('meta_elements_score', 'Meta Elements'),
            ('structured_data_score', 'Structured Data'),
            ('mobile_signals_score', 'Mobile Signals'),
            ('video_media_score', 'Video & Media'),
        ],
        'extra_paths': {
            'meta_elements_score': ['technical_seo_audit', 'meta_elements_score'],
            'structured_data_score': ['technical_seo_audit', 'structured_data_score'],
            'mobile_signals_score': ['technical_seo_audit', 'mobile_signals_score'],
            'indexation_signals_score': ['technical_seo_audit', 'indexation_signals_score'],
            'video_media_score': ['technical_seo_audit', 'video_media_score'],
        },
    },
    'content_freshness': {
        'name': 'Content Freshness',
        'type': 'score',
        'score_field': 'overall_score',
        'score_path': ['freshness_audit', 'overall_score'],
        'issues_path': ['obsolescence_indicators'],
        'quick_wins_path': ['recommendations'],
        'extra_metrics': [
            ('evergreen_ratio', 'Evergreen Ratio'),
        ],
        'extra_paths': {
            'evergreen_ratio': ['freshness_audit', 'evergreen_ratio'],
        },
    },
    'local_seo': {
        'name': 'Local SEO',
        'type': 'score',
        'score_field': 'overall_score',
        'score_path': ['local_seo_audit', 'overall_score'],
        'issues_path': ['issues'],
        'quick_wins_path': ['recommendations'],
        'extra_metrics': [
            ('nap_consistency_score', 'NAP Consistency'),
            ('local_content_score', 'Local Content'),
        ],
        'extra_paths': {
            'nap_consistency_score': ['local_seo_audit', 'nap_consistency_score'],
            'local_content_score': ['local_seo_audit', 'local_content_score'],
            'schema_readiness_score': ['local_seo_audit', 'schema_readiness_score'],
        },
    },
    'security_content_audit': {
        'name': 'Security Content Audit',
        'type': 'score',
        'score_field': 'overall_score',
        'score_path': ['security_content_audit', 'overall_score'],
        'issues_path': ['findings'],
        'quick_wins_path': ['recommendations'],
        'extra_metrics': [
            ('data_exposure_score', 'Data Exposure'),
            ('trust_signals_score', 'Trust Signals'),
        ],
        'extra_paths': {
            'data_exposure_score': ['security_content_audit', 'data_exposure_score'],
            'trust_signals_score': ['security_content_audit', 'trust_signals_score'],
            'communication_quality_score': ['security_content_audit', 'communication_quality_score'],
        },
    },
    'ai_overview_optimization': {
        'name': 'AI Overview Optimization',
        'type': 'score',
        'score_field': 'overall_score',
        'score_path': ['ai_overview_audit', 'overall_score'],
        'issues_path': ['issues'],
        'quick_wins_path': ['recommendations'],
        'extra_metrics': [
            ('paragraph_snippet_score', 'Paragraph Snippets'),
            ('list_snippet_score', 'List Snippets'),
        ],
        'extra_paths': {
            'paragraph_snippet_score': ['ai_overview_audit', 'paragraph_snippet_score'],
            'list_snippet_score': ['ai_overview_audit', 'list_snippet_score'],
            'ai_overview_eligibility_score': ['ai_overview_audit', 'ai_overview_eligibility_score'],
        },
    },
}


# ============================================================================
# UTILITY FUNCTIONS
# ============================================================================

def get_nested_value(data: dict, path: List[str], default=None):
    """Safely get a nested dictionary value using a path list."""
    current = data
    for key in path:
        if isinstance(current, dict) and key in current:
            current = current[key]
        else:
            return default
    return current


def extract_score_from_filename(filename: str) -> Optional[int]:
    """Extract numerical score from filename prefix (e.g., '085_page.json' -> 85)."""
    match = re.match(r'^(\d{1,3})_', filename)
    if match:
        score = int(match.group(1))
        return score if 0 <= score <= 100 else None
    return None


def get_url_from_filename(filename: str) -> str:
    """Convert filename to a readable URL path."""
    # Remove score prefix and extension
    name = re.sub(r'^\d{1,3}_', '', filename)
    name = name.replace('.json', '')
    # Convert underscores back to slashes
    url = '/' + name.replace('_', '/')
    return url


def truncate_text(text: str, max_length: int = 100) -> str:
    """Truncate text with ellipsis if too long."""
    if len(text) <= max_length:
        return text
    return text[:max_length - 3] + "..."


def escape_xml(text: str) -> str:
    """Escape XML special characters for ReportLab Paragraphs."""
    if not isinstance(text, str):
        text = str(text)
    return (text
            .replace('&', '&amp;')
            .replace('<', '&lt;')
            .replace('>', '&gt;')
            .replace('"', '&quot;')
            .replace("'", '&#39;'))


def get_score_bucket(score: int) -> Tuple[str, Color]:
    """Get the bucket label and color for a score."""
    if score >= 85:
        return 'excellent', SCORE_COLORS['excellent']
    elif score >= 70:
        return 'good', SCORE_COLORS['good']
    elif score >= 50:
        return 'needs_work', SCORE_COLORS['needs_work']
    else:
        return 'poor', SCORE_COLORS['poor']


# ============================================================================
# CUSTOM FLOWABLES (Charts & Drawings)
# ============================================================================

class ScoreGauge(Flowable):
    """Circular score gauge for executive summary."""
    
    def __init__(self, score: int, size: float = 100, primary_color: Color = None):
        Flowable.__init__(self)
        self.score = score
        self.size = size
        self.primary_color = primary_color or HexColor(DEFAULT_PRIMARY_COLOR)
        self.width = size
        self.height = size
    
    def draw(self):
        # Background circle (gray)
        self.canv.setStrokeColor(HexColor("#e5e7eb"))
        self.canv.setLineWidth(8)
        self.canv.circle(self.size/2, self.size/2, self.size/2 - 10)
        
        # Score arc
        _, score_color = get_score_bucket(self.score)
        self.canv.setStrokeColor(score_color)
        self.canv.setLineWidth(8)
        
        # Draw arc from 90 degrees (top) counter-clockwise
        start_angle = 90
        extent = -3.6 * self.score  # 360 degrees = 100%
        
        from reportlab.graphics.shapes import Wedge
        
        # Use canvas arc
        x = self.size/2
        y = self.size/2
        r = self.size/2 - 10
        
        # Draw the progress arc
        self.canv.arc(
            x - r, y - r, x + r, y + r,
            start_angle, extent
        )
        
        # Score text
        self.canv.setFillColor(HexColor("#1f2937"))
        self.canv.setFont("Helvetica-Bold", self.size * 0.25)
        score_text = str(self.score)
        text_width = self.canv.stringWidth(score_text, "Helvetica-Bold", self.size * 0.25)
        self.canv.drawString(x - text_width/2, y - 5, score_text)
        
        # "/100" text
        self.canv.setFont("Helvetica", self.size * 0.12)
        self.canv.setFillColor(HexColor("#6b7280"))
        sub_text = "/100"
        sub_width = self.canv.stringWidth(sub_text, "Helvetica", self.size * 0.12)
        self.canv.drawString(x - sub_width/2, y - self.size * 0.22, sub_text)


class HorizontalScoreBar(Flowable):
    """Horizontal progress bar for scores."""
    
    def __init__(self, score: int, width: float = 200, height: float = 16, show_label: bool = True):
        Flowable.__init__(self)
        self.score = score
        self.bar_width = width
        self.bar_height = height
        self.show_label = show_label
        self.width = width + (40 if show_label else 0)
        self.height = height
    
    def draw(self):
        # Background bar
        self.canv.setFillColor(HexColor("#e5e7eb"))
        self.canv.roundRect(0, 0, self.bar_width, self.bar_height, 4, fill=1, stroke=0)
        
        # Score bar
        _, score_color = get_score_bucket(self.score)
        self.canv.setFillColor(score_color)
        filled_width = (self.score / 100) * self.bar_width
        if filled_width > 0:
            self.canv.roundRect(0, 0, filled_width, self.bar_height, 4, fill=1, stroke=0)
        
        # Score label
        if self.show_label:
            self.canv.setFillColor(HexColor("#374151"))
            self.canv.setFont("Helvetica-Bold", 10)
            self.canv.drawString(self.bar_width + 8, 3, f"{self.score}")


class SeverityBadge(Flowable):
    """Colored badge for severity levels."""
    
    def __init__(self, severity: str, width: float = 60, height: float = 18):
        Flowable.__init__(self)
        self.severity = severity.lower()
        self.badge_width = width
        self.badge_height = height
        self.width = width
        self.height = height
    
    def draw(self):
        color = SEVERITY_COLORS.get(self.severity, HexColor("#9ca3af"))
        
        # Badge background
        self.canv.setFillColor(color)
        self.canv.roundRect(0, 0, self.badge_width, self.badge_height, 4, fill=1, stroke=0)
        
        # Badge text
        self.canv.setFillColor(colors.white)
        self.canv.setFont("Helvetica-Bold", 8)
        text = self.severity.upper()
        text_width = self.canv.stringWidth(text, "Helvetica-Bold", 8)
        self.canv.drawString(
            (self.badge_width - text_width) / 2,
            5,
            text
        )


def create_histogram_chart(score_distribution: Dict[str, int], width: float = 400, height: float = 200) -> Drawing:
    """Create a score distribution histogram."""
    drawing = Drawing(width, height)
    
    # Data preparation
    labels = list(score_distribution.keys())
    values = list(score_distribution.values())
    
    if not values or sum(values) == 0:
        return drawing
    
    # Create bar chart
    chart = VerticalBarChart()
    chart.x = 50
    chart.y = 30
    chart.width = width - 80
    chart.height = height - 60
    
    chart.data = [values]
    chart.categoryAxis.categoryNames = labels
    chart.categoryAxis.labels.fontName = 'Helvetica'
    chart.categoryAxis.labels.fontSize = 9
    chart.categoryAxis.labels.angle = 0
    
    chart.valueAxis.valueMin = 0
    chart.valueAxis.valueMax = max(values) * 1.2 if values else 10
    chart.valueAxis.labels.fontName = 'Helvetica'
    chart.valueAxis.labels.fontSize = 9
    
    # Bar colors based on score range
    bucket_colors = [
        SCORE_COLORS['poor'],
        SCORE_COLORS['needs_work'],
        SCORE_COLORS['good'],
        SCORE_COLORS['excellent'],
    ]
    
    chart.bars[0].fillColor = HexColor(DEFAULT_PRIMARY_COLOR)
    for i, label in enumerate(labels):
        if '0' in label or '25' in label or '49' in label:
            chart.bars[0].fillColor = SCORE_COLORS['poor']
        elif '50' in label or '69' in label:
            chart.bars[0].fillColor = SCORE_COLORS['needs_work']
    
    # Apply colors per bar
    for i in range(len(values)):
        if i < len(bucket_colors):
            chart.bars[0].fillColor = bucket_colors[min(i, len(bucket_colors)-1)]
    
    drawing.add(chart)
    return drawing


def create_pie_chart(data: Dict[str, int], width: float = 250, height: float = 200, 
                     colors_map: Dict[str, Color] = None) -> Drawing:
    """Create a pie chart for severity distribution."""
    drawing = Drawing(width, height)
    
    labels = list(data.keys())
    values = list(data.values())
    
    if not values or sum(values) == 0:
        return drawing
    
    pie = Pie()
    pie.x = width / 2 - 60
    pie.y = 20
    pie.width = 120
    pie.height = 120
    pie.data = values
    pie.labels = [f"{l}: {v}" for l, v in zip(labels, values)]
    
    # Apply colors
    if colors_map:
        pie_colors = [colors_map.get(l.lower(), HexColor("#9ca3af")) for l in labels]
    else:
        pie_colors = [
            HexColor("#ef4444"), HexColor("#f97316"), 
            HexColor("#eab308"), HexColor("#22c55e"),
            HexColor("#3b82f6"), HexColor("#8b5cf6")
        ]
    
    for i, color in enumerate(pie_colors[:len(values)]):
        pie.slices[i].fillColor = color
        pie.slices[i].strokeWidth = 1
        pie.slices[i].strokeColor = colors.white
    
    pie.slices.fontName = 'Helvetica'
    pie.slices.fontSize = 8
    
    drawing.add(pie)
    return drawing


def create_horizontal_bar_chart(data: Dict[str, int], width: float = 400, height: float = 150,
                                 primary_color: Color = None) -> Drawing:
    """Create a horizontal bar chart for issue frequency."""
    drawing = Drawing(width, height)
    
    if not data:
        return drawing
    
    # Sort by value descending and take top 8
    sorted_items = sorted(data.items(), key=lambda x: x[1], reverse=True)[:8]
    labels = [truncate_text(item[0], 30) for item in sorted_items]
    values = [item[1] for item in sorted_items]
    
    if not values:
        return drawing
    
    chart = HorizontalBarChart()
    chart.x = 120
    chart.y = 10
    chart.width = width - 140
    chart.height = height - 30
    
    chart.data = [values]
    chart.categoryAxis.categoryNames = labels
    chart.categoryAxis.labels.fontName = 'Helvetica'
    chart.categoryAxis.labels.fontSize = 8
    chart.categoryAxis.labels.dx = -5
    
    chart.valueAxis.valueMin = 0
    chart.valueAxis.valueMax = max(values) * 1.2 if values else 10
    chart.valueAxis.labels.fontName = 'Helvetica'
    chart.valueAxis.labels.fontSize = 8
    
    chart.bars[0].fillColor = primary_color or HexColor(DEFAULT_PRIMARY_COLOR)
    
    drawing.add(chart)
    return drawing


# ============================================================================
# PDF DOCUMENT CLASS
# ============================================================================

class AuditReportDocument:
    """Main class for generating audit PDF reports."""
    
    def __init__(self, 
                 website: str,
                 audit_type: str,
                 output_dir: str,
                 results_dir: str = None,
                 cross_ref_file: str = None,
                 logo_path: str = None,
                 company_name: str = None,
                 author_name: str = None,
                 primary_color: str = DEFAULT_PRIMARY_COLOR,
                 language: str = "en",
                 page_size: str = "A4",
                 include_appendix: bool = False,
                 top_n: int = 20,
                 preview: bool = False):
        
        self.website = website
        self.audit_type = audit_type.upper()
        self.audit_type_key = audit_type.lower()
        self.output_dir = Path(output_dir)
        self.results_dir = Path(results_dir) if results_dir else self._find_results_dir()
        self.cross_ref_file = Path(cross_ref_file) if cross_ref_file else self._find_cross_ref_file()
        self.logo_path = Path(logo_path) if logo_path and Path(logo_path).exists() else None
        self.company_name = company_name or "Website LLM Analyzer"
        self.author_name = author_name or "Audit Team"
        self.primary_color = HexColor(primary_color)
        self.language = language if language in TRANSLATIONS else "en"
        self.page_size = LETTER if page_size.upper() == "LETTER" else A4
        self.include_appendix = include_appendix
        self.top_n = top_n
        self.preview = preview
        
        # Get translations
        self.t = TRANSLATIONS[self.language]
        
        # Get audit config
        self.audit_config = AUDIT_CONFIGS.get(self.audit_type_key, AUDIT_CONFIGS.get('seo_audit'))
        
        # Data containers
        self.page_results: List[Dict] = []
        self.cross_ref_data: Dict = {}
        self.all_issues: List[Dict] = []
        self.statistics: Dict = {}
        
        # PDF state
        self.page_number = 0
        self.toc_entries: List[Tuple[str, int]] = []
        
        # Setup styles
        self._setup_styles()
    
    def _find_results_dir(self) -> Optional[Path]:
        """Find the results directory for the audit."""
        # Try common patterns
        patterns = [
            f"output/{self.website}_{self.audit_type}",
            f"output/{self.website}/{self.audit_type}",
            f"results/{self.website}_{self.audit_type}",
            f"results/{self.website}/{self.audit_type}",
        ]
        
        for pattern in patterns:
            path = Path(pattern)
            if path.exists():
                return path
        
        return None
    
    def _find_cross_ref_file(self) -> Optional[Path]:
        """Find the cross-reference analysis file."""
        if self.results_dir:
            # Look for cross_reference.json in results dir
            cross_ref = self.results_dir / "cross_reference.json"
            if cross_ref.exists():
                return cross_ref
            
            # Look in parent directory
            cross_ref = self.results_dir.parent / f"{self.website}_{self.audit_type}_cross_reference.json"
            if cross_ref.exists():
                return cross_ref
        
        return None
    
    def _setup_styles(self):
        """Setup paragraph styles for the document."""
        self.styles = getSampleStyleSheet()
        
        # Title style
        self.styles.add(ParagraphStyle(
            'ReportTitle',
            parent=self.styles['Title'],
            fontSize=28,
            leading=34,
            textColor=HexColor("#1f2937"),
            spaceAfter=20,
            alignment=TA_CENTER,
        ))
        
        # Subtitle
        self.styles.add(ParagraphStyle(
            'ReportSubtitle',
            parent=self.styles['Normal'],
            fontSize=16,
            leading=20,
            textColor=HexColor("#4b5563"),
            spaceAfter=12,
            alignment=TA_CENTER,
        ))
        
        # Section heading
        self.styles.add(ParagraphStyle(
            'SectionHeading',
            parent=self.styles['Heading1'],
            fontSize=18,
            leading=22,
            textColor=self.primary_color,
            spaceBefore=20,
            spaceAfter=12,
            borderPadding=(0, 0, 5, 0),
        ))
        
        # Subsection heading
        self.styles.add(ParagraphStyle(
            'SubsectionHeading',
            parent=self.styles['Heading2'],
            fontSize=14,
            leading=18,
            textColor=HexColor("#374151"),
            spaceBefore=15,
            spaceAfter=8,
        ))
        
        # Body text
        self.styles.add(ParagraphStyle(
            'ReportBody',
            parent=self.styles['Normal'],
            fontSize=10,
            leading=14,
            textColor=HexColor("#374151"),
            spaceAfter=8,
            alignment=TA_JUSTIFY,
        ))
        
        # Key finding bullet
        self.styles.add(ParagraphStyle(
            'KeyFinding',
            parent=self.styles['Normal'],
            fontSize=11,
            leading=15,
            textColor=HexColor("#1f2937"),
            leftIndent=20,
            bulletIndent=0,
            spaceAfter=6,
        ))
        
        # Table header
        self.styles.add(ParagraphStyle(
            'TableHeader',
            parent=self.styles['Normal'],
            fontSize=9,
            leading=12,
            textColor=colors.white,
            alignment=TA_LEFT,
        ))
        
        # Table cell
        self.styles.add(ParagraphStyle(
            'TableCell',
            parent=self.styles['Normal'],
            fontSize=9,
            leading=12,
            textColor=HexColor("#374151"),
        ))
        
        # Footer
        self.styles.add(ParagraphStyle(
            'Footer',
            parent=self.styles['Normal'],
            fontSize=8,
            textColor=HexColor("#9ca3af"),
            alignment=TA_CENTER,
        ))
        
        # Page URL header
        self.styles.add(ParagraphStyle(
            'PageURL',
            parent=self.styles['Normal'],
            fontSize=12,
            leading=16,
            textColor=self.primary_color,
            fontName='Helvetica-Bold',
            spaceAfter=4,
        ))
    
    def load_data(self):
        """Load all audit data from JSON files."""
        logger.info(f"Loading data for {self.website} - {self.audit_type}")
        
        # Load cross-reference data if available
        if self.cross_ref_file and self.cross_ref_file.exists():
            try:
                with open(self.cross_ref_file, 'r', encoding='utf-8') as f:
                    self.cross_ref_data = json.load(f)
                logger.info(f"Loaded cross-reference data from {self.cross_ref_file}")
            except Exception as e:
                logger.warning(f"Could not load cross-reference file: {e}")
        
        # Load individual page results
        if self.results_dir and self.results_dir.exists():
            json_files = sorted(self.results_dir.glob("*.json"))
            
            for json_file in json_files:
                # Skip cross-reference and meta files
                if 'cross_reference' in json_file.name or json_file.name.startswith('_'):
                    continue
                
                try:
                    with open(json_file, 'r', encoding='utf-8') as f:
                        data = json.load(f)
                    
                    # Extract score from filename or data
                    score = extract_score_from_filename(json_file.name)
                    if score is None:
                        score = self._extract_score_from_data(data)
                    
                    # Get URL
                    url = data.get('url', get_url_from_filename(json_file.name))
                    
                    # Extract issues
                    issues = self._extract_issues_from_data(data)
                    
                    # Extract quick wins
                    quick_wins = self._extract_quick_wins_from_data(data)
                    
                    page_result = {
                        'filename': json_file.name,
                        'url': url,
                        'score': score,
                        'data': data,
                        'issues': issues,
                        'quick_wins': quick_wins,
                    }
                    
                    # Add extra metrics if available
                    if self.audit_config.get('extra_paths'):
                        for key, path in self.audit_config['extra_paths'].items():
                            page_result[key] = get_nested_value(data, path)
                    
                    self.page_results.append(page_result)
                    self.all_issues.extend(issues)
                    
                except Exception as e:
                    logger.warning(f"Could not load {json_file}: {e}")
            
            logger.info(f"Loaded {len(self.page_results)} page results")
        
        # Calculate statistics
        self._calculate_statistics()
    
    @staticmethod
    def _safe_int(value) -> Optional[int]:
        """Safely convert a value to int, handling strings like '58' and '/100' suffixes."""
        if value is None:
            return None
        if isinstance(value, (int, float)):
            return int(value)
        if isinstance(value, str):
            cleaned = value.strip().split('/')[0].strip()
            try:
                return int(float(cleaned))
            except (ValueError, TypeError):
                return None
        return None

    def _extract_score_from_data(self, data: dict) -> Optional[int]:
        """Extract score from JSON data based on audit type."""
        config = self.audit_config

        if config['type'] in ('score', 'kantar'):
            score_path = config.get('score_path', [])
            score = get_nested_value(data, score_path)
            result = self._safe_int(score)
            if result is not None:
                return result
        elif config['type'] == 'violation':
            violations = get_nested_value(data, config.get('violations_path', []), [])
            # For violations, return inverted score (0 violations = 100)
            return max(0, 100 - len(violations) * 10) if isinstance(violations, list) else None
        elif config['type'] == 'error_count':
            errors = get_nested_value(data, config.get('errors_path', []), [])
            return max(0, 100 - len(errors) * 5) if isinstance(errors, list) else None

        return None
    
    def _extract_issues_from_data(self, data: dict) -> List[dict]:
        """Extract issues from JSON data."""
        config = self.audit_config
        
        if config['type'] == 'score':
            issues_path = config.get('issues_path', ['issues'])
            return get_nested_value(data, issues_path, []) or []
        elif config['type'] == 'violation':
            return get_nested_value(data, config.get('violations_path', []), []) or []
        elif config['type'] == 'error_count':
            return get_nested_value(data, config.get('errors_path', []), []) or []
        
        return []
    
    def _extract_quick_wins_from_data(self, data: dict) -> List[str]:
        """Extract quick wins from JSON data."""
        config = self.audit_config
        quick_wins_path = config.get('quick_wins_path', [])
        
        if quick_wins_path:
            wins = get_nested_value(data, quick_wins_path, [])
            if isinstance(wins, list):
                return [str(w) for w in wins if w]
        
        return []
    
    def _calculate_statistics(self):
        """Calculate aggregate statistics from page results."""
        scores = [p['score'] for p in self.page_results if p['score'] is not None]
        
        if scores:
            self.statistics = {
                'total_pages': len(self.page_results),
                'average_score': round(sum(scores) / len(scores), 1),
                'median_score': sorted(scores)[len(scores) // 2],
                'min_score': min(scores),
                'max_score': max(scores),
                'excellent_count': len([s for s in scores if s >= 85]),
                'good_count': len([s for s in scores if 70 <= s < 85]),
                'needs_work_count': len([s for s in scores if 50 <= s < 70]),
                'poor_count': len([s for s in scores if s < 50]),
                'total_issues': len(self.all_issues),
            }
            
            # Score distribution
            self.statistics['score_distribution'] = {
                '0-49': self.statistics['poor_count'],
                '50-69': self.statistics['needs_work_count'],
                '70-84': self.statistics['good_count'],
                '85-100': self.statistics['excellent_count'],
            }
            
            # Issue severity breakdown
            severity_counts = Counter()
            category_counts = Counter()
            
            for issue in self.all_issues:
                severity = issue.get('severity', issue.get('priority', 'minor'))
                severity_counts[str(severity).lower()] += 1
                
                category = issue.get('category', issue.get('type', 'general'))
                category_counts[str(category).lower()] += 1
            
            self.statistics['severity_breakdown'] = dict(severity_counts)
            self.statistics['category_breakdown'] = dict(category_counts)
        else:
            self.statistics = {
                'total_pages': len(self.page_results),
                'average_score': 0,
                'total_issues': len(self.all_issues),
            }
        
        # Use cross-ref data if available
        if self.cross_ref_data:
            cross_stats = self.cross_ref_data.get('cross_reference_analysis', {}).get('statistics', {})
            if cross_stats:
                self.statistics.update({
                    'average_score': cross_stats.get('average_score', self.statistics.get('average_score', 0)),
                    'median_score': cross_stats.get('median_score', self.statistics.get('median_score', 0)),
                })
    
    def generate(self, output_path: str = None):
        """Generate the PDF report."""
        if not output_path:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            output_path = self.output_dir / f"{self.website}_{self.audit_type}_report_{timestamp}.pdf"
        
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        logger.info(f"Generating PDF report: {output_path}")
        
        # Create document
        doc = SimpleDocTemplate(
            str(output_path),
            pagesize=self.page_size,
            rightMargin=2*cm,
            leftMargin=2*cm,
            topMargin=2.5*cm,
            bottomMargin=2.5*cm,
        )
        
        # Build story (content)
        story = []
        
        # Cover page
        story.extend(self._build_cover_page())
        story.append(PageBreak())
        
        # Executive summary
        story.extend(self._build_executive_summary())
        story.append(PageBreak())
        
        # Score distribution
        story.extend(self._build_score_distribution())
        
        if self.preview:
            # Preview mode: only first 5 pages
            story.append(PageBreak())
            story.extend(self._build_detailed_results(limit=5))
        else:
            story.append(PageBreak())
            
            # Detailed results
            story.extend(self._build_detailed_results())
            story.append(PageBreak())
            
            # Methodology
            story.extend(self._build_methodology())
            
            # Appendix (optional)
            if self.include_appendix:
                story.append(PageBreak())
                story.extend(self._build_appendix())
        
        # Build PDF with custom page handling
        doc.build(story, onFirstPage=self._add_page_header_footer, 
                  onLaterPages=self._add_page_header_footer)
        
        logger.info(f"PDF report generated: {output_path}")
        return output_path
    
    def _add_page_header_footer(self, canvas, doc):
        """Add header and footer to each page."""
        canvas.saveState()
        
        page_width, page_height = self.page_size
        
        # Header line
        canvas.setStrokeColor(HexColor("#e5e7eb"))
        canvas.setLineWidth(0.5)
        canvas.line(2*cm, page_height - 2*cm, page_width - 2*cm, page_height - 2*cm)
        
        # Header text
        canvas.setFillColor(HexColor("#6b7280"))
        canvas.setFont("Helvetica", 8)
        canvas.drawString(2*cm, page_height - 1.7*cm, f"{self.website} | {self.audit_config['name']}")
        canvas.drawRightString(page_width - 2*cm, page_height - 1.7*cm, f"{self.t['page']} {doc.page}")
        
        # Footer line
        canvas.line(2*cm, 2*cm, page_width - 2*cm, 2*cm)
        
        # Footer text
        canvas.drawCentredString(page_width / 2, 1.5*cm, f"{self.t['generated_by']} | {self.t['confidential']}")
        
        canvas.restoreState()
    
    def _build_cover_page(self) -> List:
        """Build the cover page content."""
        story = []
        page_width = self.page_size[0] - 4*cm
        
        # Spacer for vertical centering
        story.append(Spacer(1, 4*cm))
        
        # Logo (if provided)
        if self.logo_path:
            try:
                logo = Image(str(self.logo_path), width=5*cm, height=2*cm)
                logo.hAlign = 'CENTER'
                story.append(logo)
                story.append(Spacer(1, 1.5*cm))
            except Exception as e:
                logger.warning(f"Could not load logo: {e}")
        
        # Title
        story.append(Paragraph(
            self.t['website_audit_report'].upper(),
            self.styles['ReportTitle']
        ))
        
        # Subtitle (audit type)
        story.append(Paragraph(
            f"{self.audit_config['name']} — {self.website}",
            self.styles['ReportSubtitle']
        ))
        
        story.append(Spacer(1, 3*cm))
        
        # Metadata table
        date_str = datetime.now().strftime("%B %d, %Y")
        meta_data = [
            [self.t['date'] + ":", date_str],
            [self.t['prepared_by'] + ":", self.author_name],
            [self.t['audit_type'] + ":", self.audit_config['name']],
        ]
        
        meta_table = Table(meta_data, colWidths=[4*cm, 6*cm])
        meta_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 11),
            ('TEXTCOLOR', (0, 0), (-1, -1), HexColor("#374151")),
            ('ALIGN', (0, 0), (0, -1), 'RIGHT'),
            ('ALIGN', (1, 0), (1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        meta_table.hAlign = 'CENTER'
        story.append(meta_table)
        
        story.append(Spacer(1, 4*cm))
        
        # Confidential notice
        story.append(Paragraph(
            self.t['confidential'].upper(),
            ParagraphStyle(
                'Confidential',
                parent=self.styles['Normal'],
                fontSize=10,
                textColor=HexColor("#9ca3af"),
                alignment=TA_CENTER,
            )
        ))
        
        # Company name
        story.append(Spacer(1, 1*cm))
        story.append(Paragraph(
            self.company_name,
            ParagraphStyle(
                'CompanyName',
                parent=self.styles['Normal'],
                fontSize=12,
                textColor=self.primary_color,
                fontName='Helvetica-Bold',
                alignment=TA_CENTER,
            )
        ))
        
        return story
    
    def _build_executive_summary(self) -> List:
        """Build the executive summary page."""
        story = []
        page_width = self.page_size[0] - 4*cm
        
        # Section heading
        story.append(Paragraph(self.t['executive_summary'], self.styles['SectionHeading']))
        
        # Score gauge and summary stats side by side
        avg_score = int(self.statistics.get('average_score', 0))
        
        # Create a table with gauge on left, stats on right
        gauge = ScoreGauge(avg_score, size=120, primary_color=self.primary_color)
        
        # Stats content
        stats_items = [
            f"<b>{self.t['pages_analyzed']}:</b> {self.statistics.get('total_pages', 0)}",
            f"<b>{self.t['overall_score']}:</b> {avg_score}/100",
            f"<b>Min/Max:</b> {self.statistics.get('min_score', 0)} - {self.statistics.get('max_score', 0)}",
            f"<b>Total Issues:</b> {self.statistics.get('total_issues', 0)}",
        ]
        
        stats_content = []
        for item in stats_items:
            stats_content.append([Paragraph(item, self.styles['ReportBody'])])
        
        stats_table = Table(stats_content, colWidths=[8*cm])
        stats_table.setStyle(TableStyle([
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]))
        
        summary_table = Table(
            [[gauge, stats_table]],
            colWidths=[5*cm, page_width - 6*cm]
        )
        summary_table.setStyle(TableStyle([
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('ALIGN', (0, 0), (0, 0), 'CENTER'),
        ]))
        
        story.append(summary_table)
        story.append(Spacer(1, 1*cm))
        
        # Key findings
        story.append(Paragraph(self.t['key_findings'], self.styles['SubsectionHeading']))
        
        findings = self._generate_key_findings()
        for finding in findings[:6]:  # Limit to 6 findings
            story.append(Paragraph(
                f"• {escape_xml(finding)}",
                self.styles['KeyFinding']
            ))
        
        story.append(Spacer(1, 1*cm))
        
        # Score distribution mini chart
        story.append(Paragraph(self.t['score_distribution'], self.styles['SubsectionHeading']))
        
        dist = self.statistics.get('score_distribution', {})
        if dist and sum(dist.values()) > 0:
            # Create colored boxes for distribution
            dist_data = []
            colors_list = [SCORE_COLORS['poor'], SCORE_COLORS['needs_work'], 
                          SCORE_COLORS['good'], SCORE_COLORS['excellent']]
            
            for i, (label, count) in enumerate(dist.items()):
                pct = round(100 * count / self.statistics['total_pages'], 1) if self.statistics['total_pages'] > 0 else 0
                dist_data.append([label, f"{count} ({pct}%)"])
            
            dist_table = Table(dist_data, colWidths=[3*cm, 4*cm])
            dist_table.setStyle(TableStyle([
                ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('TEXTCOLOR', (0, 0), (-1, -1), HexColor("#374151")),
                ('BACKGROUND', (0, 0), (0, 0), SCORE_COLORS['poor']),
                ('BACKGROUND', (0, 1), (0, 1), SCORE_COLORS['needs_work']),
                ('BACKGROUND', (0, 2), (0, 2), SCORE_COLORS['good']),
                ('BACKGROUND', (0, 3), (0, 3), SCORE_COLORS['excellent']),
                ('TEXTCOLOR', (0, 0), (0, -1), colors.white),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('ALIGN', (0, 0), (0, -1), 'CENTER'),
                ('ALIGN', (1, 0), (1, -1), 'LEFT'),
                ('TOPPADDING', (0, 0), (-1, -1), 6),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                ('LEFTPADDING', (0, 0), (-1, -1), 8),
            ]))
            
            story.append(dist_table)
        
        # Quick wins section (if available)
        all_quick_wins = []
        for page in self.page_results[:20]:
            all_quick_wins.extend(page.get('quick_wins', []))
        
        # Also check cross-ref data
        if self.cross_ref_data:
            llm_analysis = self.cross_ref_data.get('cross_reference_analysis', {}).get('llm_analysis', {})
            all_quick_wins.extend(llm_analysis.get('quick_wins', []))
        
        if all_quick_wins:
            story.append(Spacer(1, 0.8*cm))
            story.append(Paragraph(self.t['quick_wins'], self.styles['SubsectionHeading']))
            
            # Deduplicate and limit
            seen = set()
            unique_wins = []
            for win in all_quick_wins:
                if win and win not in seen:
                    seen.add(win)
                    unique_wins.append(win)
            
            for win in unique_wins[:5]:
                story.append(Paragraph(
                    f"• {escape_xml(win)}",
                    self.styles['KeyFinding']
                ))
        
        return story
    
    def _generate_key_findings(self) -> List[str]:
        """Generate key findings text from statistics."""
        findings = []
        stats = self.statistics
        
        if 'excellent_count' in stats:
            findings.append(f"{stats['excellent_count']} pages scored 'Excellent' (85+)")
        
        if 'poor_count' in stats and stats['poor_count'] > 0:
            findings.append(f"{stats['poor_count']} pages need immediate attention (below 50)")
        
        # Issue category findings
        if 'category_breakdown' in stats:
            top_categories = sorted(stats['category_breakdown'].items(), key=lambda x: x[1], reverse=True)[:3]
            for cat, count in top_categories:
                findings.append(f"{count} issues related to '{cat}'")
        
        # Severity findings
        if 'severity_breakdown' in stats:
            critical = stats['severity_breakdown'].get('critical', 0)
            if critical > 0:
                findings.append(f"{critical} critical issues require urgent action")
            
            major = stats['severity_breakdown'].get('major', 0) + stats['severity_breakdown'].get('high', 0)
            if major > 0:
                findings.append(f"{major} major issues identified")
        
        # Cross-ref insights
        if self.cross_ref_data:
            analysis = self.cross_ref_data.get('cross_reference_analysis', {})
            llm = analysis.get('llm_analysis', {})
            
            # Site-wide issues
            site_issues = llm.get('site_wide_issues', [])
            if site_issues:
                findings.append(f"{len(site_issues)} site-wide issues identified")
            
            # Content gaps
            gaps = llm.get('content_gaps', [])
            if gaps:
                high_priority = [g for g in gaps if g.get('priority') == 'high']
                if high_priority:
                    findings.append(f"{len(high_priority)} high-priority content gaps identified")
        
        return findings
    
    def _build_score_distribution(self) -> List:
        """Build the score distribution detail page."""
        story = []
        page_width = self.page_size[0] - 4*cm
        
        story.append(Paragraph(self.t['score_distribution'], self.styles['SectionHeading']))
        
        # Histogram chart
        dist = self.statistics.get('score_distribution', {})
        if dist and sum(dist.values()) > 0:
            chart = create_histogram_chart(dist, width=page_width, height=180)
            story.append(chart)
        
        story.append(Spacer(1, 1*cm))
        
        # Top pages table
        story.append(Paragraph(self.t['top_pages'], self.styles['SubsectionHeading']))
        
        top_pages = sorted([p for p in self.page_results if p['score'] is not None], 
                          key=lambda x: x['score'], reverse=True)[:10]
        
        if top_pages:
            top_data = [[self.t['url'], self.t['score']]]
            for page in top_pages:
                top_data.append([
                    truncate_text(page['url'], 60),
                    str(page['score'])
                ])
            
            top_table = Table(top_data, colWidths=[page_width - 3*cm, 2.5*cm])
            top_table.setStyle(self._get_table_style())
            story.append(top_table)
        
        story.append(Spacer(1, 1*cm))
        
        # Bottom pages table
        story.append(Paragraph(self.t['bottom_pages'], self.styles['SubsectionHeading']))
        
        bottom_pages = sorted([p for p in self.page_results if p['score'] is not None], 
                             key=lambda x: x['score'])[:10]
        
        if bottom_pages:
            bottom_data = [[self.t['url'], self.t['score']]]
            for page in bottom_pages:
                bottom_data.append([
                    truncate_text(page['url'], 60),
                    str(page['score'])
                ])
            
            bottom_table = Table(bottom_data, colWidths=[page_width - 3*cm, 2.5*cm])
            bottom_table.setStyle(self._get_table_style())
            story.append(bottom_table)
        
        # Issues by category chart
        if 'category_breakdown' in self.statistics and self.statistics['category_breakdown']:
            story.append(Spacer(1, 1*cm))
            story.append(Paragraph(self.t['issues_by_category'], self.styles['SubsectionHeading']))
            
            chart = create_horizontal_bar_chart(
                self.statistics['category_breakdown'],
                width=page_width,
                height=150,
                primary_color=self.primary_color
            )
            story.append(chart)
        
        return story
    
    def _build_detailed_results(self, limit: int = None) -> List:
        """Build detailed per-page results."""
        story = []
        page_width = self.page_size[0] - 4*cm
        
        story.append(Paragraph(self.t['detailed_results'], self.styles['SectionHeading']))
        
        # Sort pages: top_n highest, then bottom 10
        sorted_pages = sorted([p for p in self.page_results if p['score'] is not None],
                             key=lambda x: x['score'], reverse=True)
        
        if limit:
            pages_to_show = sorted_pages[:limit]
        else:
            top_pages = sorted_pages[:self.top_n]
            bottom_pages = sorted_pages[-10:] if len(sorted_pages) > self.top_n else []
            # Remove duplicates if bottom overlaps with top
            bottom_urls = {p['url'] for p in top_pages}
            bottom_pages = [p for p in bottom_pages if p['url'] not in bottom_urls]
            pages_to_show = top_pages + bottom_pages
        
        for i, page in enumerate(pages_to_show):
            page_content = self._build_page_result(page, page_width)
            
            # Keep page content together if possible
            story.append(KeepTogether(page_content))
            
            if i < len(pages_to_show) - 1:
                story.append(Spacer(1, 0.8*cm))
        
        return story
    
    def _build_page_result(self, page: Dict, page_width: float) -> List:
        """Build content for a single page result."""
        content = []
        
        # Page URL/title
        content.append(Paragraph(
            escape_xml(truncate_text(page['url'], 80)),
            self.styles['PageURL']
        ))
        
        # Score bar
        if page['score'] is not None:
            score_bar = HorizontalScoreBar(page['score'], width=page_width * 0.6)
            content.append(score_bar)
            content.append(Spacer(1, 0.3*cm))
        
        # Extra metrics (for score-based audits)
        extra_metrics = self.audit_config.get('extra_metrics', [])
        if extra_metrics:
            metrics_data = []
            for key, label in extra_metrics:
                value = page.get(key)
                if value is not None:
                    metrics_data.append(f"{label}: {value}")
            
            if metrics_data:
                content.append(Paragraph(
                    " | ".join(metrics_data),
                    ParagraphStyle('Metrics', parent=self.styles['ReportBody'], fontSize=9, textColor=HexColor("#6b7280"))
                ))
                content.append(Spacer(1, 0.3*cm))
        
        # Issues table
        issues = page.get('issues', [])
        if issues:
            content.append(Paragraph(f"<b>{self.t['issues']}</b> ({len(issues)})", self.styles['ReportBody']))
            
            issues_data = [[self.t['severity'], self.t['issue'], self.t['recommendation']]]
            
            for issue in issues[:8]:  # Limit to 8 issues per page
                severity = issue.get('severity', issue.get('priority', 'minor'))
                issue_text = issue.get('issue', issue.get('description', issue.get('fragment', '')))
                recommendation = issue.get('recommendation', issue.get('mitigation_suggestion', ''))
                
                issues_data.append([
                    str(severity).capitalize(),
                    truncate_text(str(issue_text), 50),
                    truncate_text(str(recommendation), 50),
                ])
            
            issues_table = Table(issues_data, colWidths=[2*cm, 6*cm, 6*cm])
            issues_table.setStyle(self._get_issues_table_style())
            content.append(issues_table)
        
        # Quick wins
        quick_wins = page.get('quick_wins', [])
        if quick_wins:
            content.append(Spacer(1, 0.3*cm))
            content.append(Paragraph(f"<b>{self.t['quick_wins']}:</b>", self.styles['ReportBody']))
            for win in quick_wins[:3]:
                content.append(Paragraph(f"• {escape_xml(win)}", self.styles['KeyFinding']))
        
        return content
    
    def _build_methodology(self) -> List:
        """Build the methodology section."""
        story = []
        
        story.append(Paragraph(self.t['methodology'], self.styles['SectionHeading']))
        
        methodology_text = f"""
        This audit was performed using the Website LLM Analyzer tool with the following configuration:
        
        <b>Audit Type:</b> {self.audit_config['name']}<br/>
        <b>Date:</b> {datetime.now().strftime("%Y-%m-%d")}<br/>
        <b>Pages in Scope:</b> {self.statistics.get('total_pages', 'N/A')}<br/>
        <b>Website:</b> {self.website}<br/>
        """
        
        story.append(Paragraph(methodology_text, self.styles['ReportBody']))
        story.append(Spacer(1, 0.5*cm))
        
        # Scoring methodology
        scoring_text = """
        <b>Scoring Methodology:</b><br/><br/>
        
        • <b>Overall Score:</b> Weighted average based on audit-specific criteria<br/>
        • <b>Excellent (85-100):</b> Page meets all major requirements with minor or no issues<br/>
        • <b>Good (70-84):</b> Page meets most requirements with some improvements needed<br/>
        • <b>Needs Work (50-69):</b> Page has significant issues that should be addressed<br/>
        • <b>Poor (0-49):</b> Page requires immediate attention and major improvements<br/><br/>
        
        <b>Issue Severity Levels:</b><br/><br/>
        
        • <b>Critical:</b> Issues that severely impact user experience or compliance<br/>
        • <b>Major:</b> Significant issues that should be addressed promptly<br/>
        • <b>Minor:</b> Small improvements that would enhance quality<br/>
        • <b>Opportunity:</b> Suggestions for optimization and enhancement<br/>
        """
        
        story.append(Paragraph(scoring_text, self.styles['ReportBody']))
        
        return story
    
    def _build_appendix(self) -> List:
        """Build the appendix with full page list."""
        story = []
        page_width = self.page_size[0] - 4*cm
        
        story.append(Paragraph(self.t['appendix'] + ": " + self.t['full_page_list'], self.styles['SectionHeading']))
        
        # Sort all pages by score
        all_pages = sorted([p for p in self.page_results if p['score'] is not None],
                          key=lambda x: x['score'], reverse=True)
        
        # Create compact table
        table_data = [[self.t['url'], self.t['score']]]
        
        for page in all_pages:
            table_data.append([
                truncate_text(page['url'], 70),
                str(page['score'])
            ])
        
        # Split into chunks for better pagination
        chunk_size = 40
        for i in range(0, len(table_data), chunk_size):
            chunk = table_data[i:i+chunk_size]
            if i > 0:
                chunk.insert(0, table_data[0])  # Add header
            
            table = Table(chunk, colWidths=[page_width - 2*cm, 1.5*cm])
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), self.primary_color),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 8),
                ('ALIGN', (1, 0), (1, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('GRID', (0, 0), (-1, -1), 0.5, HexColor("#e5e7eb")),
                ('TOPPADDING', (0, 0), (-1, -1), 4),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, HexColor("#f9fafb")]),
            ]))
            story.append(table)
            
            if i + chunk_size < len(table_data):
                story.append(PageBreak())
        
        return story
    
    def _get_table_style(self) -> TableStyle:
        """Get standard table style."""
        return TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), self.primary_color),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('ALIGN', (0, 0), (-1, 0), 'LEFT'),
            ('ALIGN', (-1, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('GRID', (0, 0), (-1, -1), 0.5, HexColor("#e5e7eb")),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, HexColor("#f9fafb")]),
        ])
    
    def _get_issues_table_style(self) -> TableStyle:
        """Get issues table style with severity coloring."""
        return TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), HexColor("#374151")),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 8),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('GRID', (0, 0), (-1, -1), 0.5, HexColor("#e5e7eb")),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ('LEFTPADDING', (0, 0), (-1, -1), 4),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, HexColor("#fef3c7")]),
        ])


# ============================================================================
# MAIN CLI
# ============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Generate professional PDF audit reports from Website LLM Analyzer results.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Basic usage
  python generate_report.py --website example.com --audit SEO_AUDIT
  
  # With branding
  python generate_report.py --website example.com --audit SEO_AUDIT \\
    --logo logo.png --company "My Agency" --author "John Doe"
  
  # Quick preview (first 5 pages only)
  python generate_report.py --website example.com --audit SEO_AUDIT --preview
  
  # Full customization
  python generate_report.py --website example.com --audit GEO_AUDIT \\
    --output report.pdf --color-scheme "#FF6600" \\
    --include-appendix --top-n 30 --language nl
        """
    )
    
    # Required arguments
    parser.add_argument('--website', required=True, help='Website domain (e.g., example.com)')
    parser.add_argument('--audit', required=True, help='Audit type (e.g., SEO_AUDIT, GEO_AUDIT)')
    
    # Output options
    parser.add_argument('--output', '-o', help='Output PDF path (default: auto-generated)')
    parser.add_argument('--output-dir', default='output', help='Output directory (default: output)')
    
    # Data sources
    parser.add_argument('--results-dir', help='Directory containing JSON results')
    parser.add_argument('--cross-ref', help='Cross-reference analysis JSON file')
    
    # Branding options
    parser.add_argument('--logo', help='Path to logo image (PNG/JPG)')
    parser.add_argument('--company', help='Company name for header')
    parser.add_argument('--author', help='Author name for cover page')
    parser.add_argument('--color-scheme', default=DEFAULT_PRIMARY_COLOR, help='Primary brand color (hex)')
    
    # Report options
    parser.add_argument('--include-appendix', action='store_true', help='Include full page list appendix')
    parser.add_argument('--top-n', type=int, default=20, help='Number of detailed page reports (default: 20)')
    parser.add_argument('--language', default='en', choices=['en', 'nl', 'ro'], help='Report language')
    parser.add_argument('--page-size', default='A4', choices=['A4', 'LETTER'], help='Page size')
    
    # Preview mode
    parser.add_argument('--preview', action='store_true', help='Generate preview (first 5 pages only)')
    
    # Debug
    parser.add_argument('--verbose', '-v', action='store_true', help='Verbose output')
    
    args = parser.parse_args()
    
    # Set up logging
    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)
    
    # Create report generator
    report = AuditReportDocument(
        website=args.website,
        audit_type=args.audit,
        output_dir=args.output_dir,
        results_dir=args.results_dir,
        cross_ref_file=args.cross_ref,
        logo_path=args.logo,
        company_name=args.company,
        author_name=args.author,
        primary_color=args.color_scheme,
        language=args.language,
        page_size=args.page_size,
        include_appendix=args.include_appendix,
        top_n=args.top_n,
        preview=args.preview,
    )
    
    # Load data
    report.load_data()
    
    # Generate PDF
    output_path = report.generate(args.output)
    
    print(f"\n✓ Report generated: {output_path}")
    if args.preview:
        print("  (Preview mode: only first 5 pages included)")


if __name__ == "__main__":
    main()
